apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-nodejs-app
  template:
    metadata:
      labels:
        app: devops-nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: yourdockerhub/devops-nodejs-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  type: NodePort
  selector:
    app: devops-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
